# Generated by Django 5.1.15 on 2026-04-10 01:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerMetricsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_id', models.CharField(db_index=True, max_length=64)),
                ('cpu_usage', models.FloatField(help_text='컨테이너 CPU 사용률 (%)')),
                ('memory_usage', models.BigIntegerField(help_text='메모리 사용량 (bytes)')),
                ('memory_limit', models.BigIntegerField(help_text='메모리 한도 (bytes)')),
                ('memory_percent', models.FloatField(help_text='메모리 사용률 (%)')),
                ('network_rx', models.BigIntegerField(help_text='누적 수신 bytes')),
                ('network_tx', models.BigIntegerField(help_text='누적 송신 bytes')),
                ('disk_read', models.BigIntegerField(help_text='누적 디스크 read bytes')),
                ('disk_write', models.BigIntegerField(help_text='누적 디스크 write bytes')),
                ('raw_data', models.JSONField(help_text='Agent로부터 받은 container_metrics 전체 payload')),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='Agent가 수집한 시각')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_metrics', to='agents.agent')),
            ],
            options={
                'db_table': 'container_metrics_history',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['agent', 'container_id', '-recorded_at'], name='container_m_agent_i_4217a3_idx'), models.Index(fields=['container_id', '-recorded_at'], name='container_m_contain_eb33af_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetricsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_usage', models.FloatField(help_text='CPU 사용률 (%)')),
                ('memory_usage', models.FloatField(help_text='메모리 사용률 (%)')),
                ('memory_used', models.BigIntegerField(help_text='사용 메모리 (MB)')),
                ('memory_total', models.BigIntegerField(help_text='전체 메모리 (MB)')),
                ('disk_usage', models.FloatField(help_text='디스크 사용률 (%)')),
                ('network_rx', models.BigIntegerField(help_text='누적 수신 bytes')),
                ('network_tx', models.BigIntegerField(help_text='누적 송신 bytes')),
                ('raw_data', models.JSONField(help_text='Agent로부터 받은 system_metrics 전체 payload')),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='Agent가 수집한 시각')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_metrics', to='agents.agent')),
            ],
            options={
                'db_table': 'system_metrics_history',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['agent', '-recorded_at'], name='system_metr_agent_i_f12b22_idx')],
            },
        ),
    ]
