# Generated by Django 5.1.15 on 2026-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_container_metrics_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containermetricshistory',
            name='gpu_usage',
            field=models.FloatField(blank=True, help_text='컨테이너 GPU 사용률 (0~100, %). Agent가 PID 매핑으로 계산. 측정 불가 시 null.', null=True),
        ),
        migrations.AlterField(
            model_name='containermetricshistory',
            name='stack',
            field=models.CharField(default='Unmanaged', help_text="라벨에서 추출한 스택 이름. 우선순위: hypercube.stack → com.docker.compose.project → working_dir → 'Unmanaged'.", max_length=128),
        ),
    ]
