# Generated by Django 5.1.15 on 2026-05-18 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_workspace_quota_capacity'),
        ('metrics', '0009_system_power_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerMetricsRollup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('container_id', models.CharField(max_length=64)),
                ('stack', models.CharField(default='Unmanaged', max_length=128)),
                ('bucket_seconds', models.IntegerField()),
                ('bucket_start', models.DateTimeField()),
                ('cpu_usage_pct_avg', models.FloatField(blank=True, null=True)),
                ('cpu_usage_pct_max', models.FloatField(blank=True, null=True)),
                ('cpu_usage_raw_avg', models.FloatField(blank=True, null=True)),
                ('cpu_usage_raw_max', models.FloatField(blank=True, null=True)),
                ('cpu_cores_quota_avg', models.FloatField(blank=True, null=True)),
                ('memory_avg', models.FloatField(blank=True, null=True)),
                ('memory_max', models.FloatField(blank=True, null=True)),
                ('memory_percent_avg', models.FloatField(blank=True, null=True)),
                ('network_rx_max', models.BigIntegerField(blank=True, null=True)),
                ('network_tx_max', models.BigIntegerField(blank=True, null=True)),
                ('disk_read_max', models.BigIntegerField(blank=True, null=True)),
                ('disk_write_max', models.BigIntegerField(blank=True, null=True)),
                ('gpu_usage_avg', models.FloatField(blank=True, null=True)),
                ('gpu_usage_max', models.FloatField(blank=True, null=True)),
                ('gpu_memory_used_avg', models.BigIntegerField(blank=True, null=True)),
                ('gpu_memory_used_max', models.BigIntegerField(blank=True, null=True)),
                ('gpu_memory_total_avg', models.BigIntegerField(blank=True, null=True)),
                ('sample_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_rollups', to='agents.agent')),
            ],
            options={
                'db_table': 'container_metrics_rollup',
                'indexes': [models.Index(fields=['agent', 'bucket_seconds', '-bucket_start'], name='container_m_agent_i_eb3922_idx'), models.Index(fields=['agent', 'stack', 'bucket_seconds', '-bucket_start'], name='cmroll_agent_stack_idx')],
                'unique_together': {('agent', 'container_id', 'bucket_seconds', 'bucket_start')},
            },
        ),
        migrations.CreateModel(
            name='StackMetricsRollup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stack', models.CharField(max_length=128)),
                ('bucket_seconds', models.IntegerField()),
                ('bucket_start', models.DateTimeField()),
                ('cpu_avg', models.FloatField(blank=True, null=True)),
                ('cpu_max', models.FloatField(blank=True, null=True)),
                ('memory_percent_avg', models.FloatField(blank=True, null=True)),
                ('memory_percent_max', models.FloatField(blank=True, null=True)),
                ('memory_bytes_avg', models.BigIntegerField(blank=True, null=True)),
                ('network_rx_max', models.BigIntegerField(blank=True, null=True)),
                ('network_tx_max', models.BigIntegerField(blank=True, null=True)),
                ('disk_read_max', models.BigIntegerField(blank=True, null=True)),
                ('disk_write_max', models.BigIntegerField(blank=True, null=True)),
                ('gpu_usage_avg', models.FloatField(blank=True, null=True)),
                ('gpu_usage_max', models.FloatField(blank=True, null=True)),
                ('gpu_memory_used_avg', models.BigIntegerField(blank=True, null=True)),
                ('gpu_memory_used_max', models.BigIntegerField(blank=True, null=True)),
                ('gpu_memory_total_avg', models.BigIntegerField(blank=True, null=True)),
                ('container_count', models.IntegerField(default=0)),
                ('sample_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_rollups', to='agents.agent')),
            ],
            options={
                'db_table': 'stack_metrics_rollup',
                'indexes': [models.Index(fields=['agent', 'bucket_seconds', '-bucket_start'], name='stack_metri_agent_i_243d95_idx')],
                'unique_together': {('agent', 'stack', 'bucket_seconds', 'bucket_start')},
            },
        ),
        migrations.CreateModel(
            name='SystemMetricsRollup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bucket_seconds', models.IntegerField(help_text='3600 (1h) 또는 86400 (1d).')),
                ('bucket_start', models.DateTimeField(help_text='bucket 시작 시각 (aware datetime).')),
                ('cpu_avg', models.FloatField(blank=True, null=True)),
                ('cpu_max', models.FloatField(blank=True, null=True)),
                ('memory_usage_avg', models.FloatField(blank=True, null=True)),
                ('memory_usage_max', models.FloatField(blank=True, null=True)),
                ('disk_usage_avg', models.FloatField(blank=True, null=True)),
                ('disk_usage_max', models.FloatField(blank=True, null=True)),
                ('network_rx_max', models.BigIntegerField(blank=True, null=True)),
                ('network_tx_max', models.BigIntegerField(blank=True, null=True)),
                ('gpu_usage_avg', models.FloatField(blank=True, null=True)),
                ('gpu_usage_max', models.FloatField(blank=True, null=True)),
                ('gpu_memory_used_avg', models.BigIntegerField(blank=True, null=True)),
                ('gpu_memory_used_max', models.BigIntegerField(blank=True, null=True)),
                ('gpu_memory_total_avg', models.BigIntegerField(blank=True, null=True)),
                ('cpu_power_w_avg', models.FloatField(blank=True, null=True)),
                ('cpu_temp_c_max', models.FloatField(blank=True, null=True)),
                ('sample_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_rollups', to='agents.agent')),
            ],
            options={
                'db_table': 'system_metrics_rollup',
                'indexes': [models.Index(fields=['agent', 'bucket_seconds', '-bucket_start'], name='system_metr_agent_i_f5fc04_idx')],
                'unique_together': {('agent', 'bucket_seconds', 'bucket_start')},
            },
        ),
    ]
