# Generated by Django 5.1.15 on 2026-05-21 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_workspace_quota_capacity'),
        ('metrics', '0010_metrics_rollups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(help_text='이벤트 발생 시점 hostname 스냅샷.', max_length=255)),
                ('metric', models.CharField(choices=[('cpu', 'CPU'), ('memory', 'Memory'), ('disk', 'Disk'), ('gpu', 'GPU')], max_length=8)),
                ('kind', models.CharField(choices=[('threshold', 'Threshold'), ('spike', 'Spike')], max_length=12)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], help_text='peak 기준 최고 심각도.', max_length=8)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='null 이면 진행 중.', null=True)),
                ('ended_reason', models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('acknowledged', 'Acknowledged')], max_length=12, null=True)),
                ('last_seen_at', models.DateTimeField(help_text='마지막으로 조건을 만족한 판정 시각.')),
                ('peak_value', models.FloatField(help_text='구간 내 최대 사용률 (%).')),
                ('last_value', models.FloatField(help_text='마지막 판정의 사용률 (%).')),
                ('spike_delta', models.FloatField(blank=True, help_text='spike 최대 증가폭 (%p). threshold 면 null.', null=True)),
                ('cause_container_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cause_container_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_resource_events', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_events', to='agents.agent')),
            ],
            options={
                'db_table': 'resource_events',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['ended_at', '-started_at'], name='resource_ev_ended_a_6e8378_idx'), models.Index(fields=['-started_at'], name='resource_ev_started_e5c6ac_idx'), models.Index(fields=['agent', 'metric', 'ended_at'], name='resource_ev_agent_i_e5554d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('agent', 'metric'), name='uniq_active_resource_event_per_agent_metric')],
            },
        ),
    ]
