# Generated by Django 5.1.15 on 2026-04-15 08:16

from django.db import migrations, models


def collapse_roles(apps, schema_editor):
    """기존 3단계(super_admin/server_admin/viewer) → 2단계(admin/user) 매핑."""
    User = apps.get_model("users", "CustomUser")
    # super_admin / server_admin → admin
    User.objects.filter(role__in=("super_admin", "server_admin")).update(role="admin")
    # viewer → user
    User.objects.filter(role="viewer").update(role="user")


def seed_test_accounts(apps, schema_editor):
    """테스트 계정 3종 시드 (이미 있으면 스킵).

    - admin/admin1234 (기존 slate 안전망, role=admin)
    - agics/agics12!@ (운영자 본인, role=admin)
    - agics1/agics12!@ (테스트 사용자, role=user)

    Django test runner가 쓰는 임시 DB에는 시드를 생성하지 않는다
    (개별 test가 자체 fixture를 만들다 unique 충돌).
    """
    import sys
    if "test" in sys.argv:
        return

    User = apps.get_model("users", "CustomUser")
    from django.contrib.auth.hashers import make_password

    seeds = [
        ("admin", "admin1234", "admin", True),  # staff+superuser 유지
        ("agics", "agics12!@", "admin", True),
        ("agics1", "agics12!@", "user", False),
    ]
    for username, password, role, is_staff in seeds:
        existing = User.objects.filter(username=username).first()
        if existing:
            # 기존 사용자는 role만 맞춰주고 비밀번호는 건드리지 않음
            if existing.role != role:
                existing.role = role
                existing.save(update_fields=["role"])
            continue
        User.objects.create(
            username=username,
            password=make_password(password),
            role=role,
            is_staff=is_staff,
            is_superuser=is_staff,
            is_active=True,
        )


def reverse_noop(apps, schema_editor):
    # 되돌리지 않음 (데이터 보존)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.RunPython(collapse_roles, reverse_noop),
        migrations.RunPython(seed_test_accounts, reverse_noop),
    ]
