# Generated by Django 5.1.15 on 2026-04-14 10:02

import secrets

from django.db import migrations, models
from django.utils import timezone


def auto_approve_pending(apps, schema_editor):
    """기존 pending Agent를 일괄 자동 승인 + token 발급."""
    Agent = apps.get_model("agents", "Agent")
    now = timezone.now()
    for agent in Agent.objects.filter(status="pending"):
        agent.status = "approved"
        agent.approved_at = agent.approved_at or now
        if not agent.token:
            agent.token = f"agent_{secrets.token_urlsafe(32)}"
        agent.save(update_fields=["status", "approved_at", "token"])


def revert_noop(apps, schema_editor):
    # 자동 승인된 항목을 pending으로 되돌리지 않음 (token 손실 위험).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.RunPython(auto_approve_pending, revert_noop),
    ]
