# Generated by Django 5.1.15 on 2026-04-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_lifecycle_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerAssignment',
        ),
    ]
