# Generated by Django 5.1.15 on 2026-05-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_drop_server_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatusEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('previous_offline_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='agents.agent')),
            ],
            options={
                'db_table': 'agent_status_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['-occurred_at'], name='agent_statu_occurre_6087f1_idx'), models.Index(fields=['agent', '-occurred_at'], name='agent_statu_agent_i_53f184_idx')],
            },
        ),
    ]
