# Generated by Django 5.1.15 on 2026-03-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('exited', 'Exited'), ('created', 'Created'), ('restarting', 'Restarting'), ('dead', 'Dead')], default='created', max_length=12)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='agents.agent')),
            ],
            options={
                'db_table': 'containers',
                'ordering': ['name'],
            },
        ),
    ]
