# Generated by Django 5.1.15 on 2026-04-15 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_drop_server_assignment'),
        ('containers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_containers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContainerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('delete', 'Delete')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('custom_name', models.CharField(blank=True, default='', max_length=255)),
                ('selected_image', models.CharField(blank=True, default='', max_length=255)),
                ('custom_env', models.JSONField(blank=True, default=dict)),
                ('custom_ports', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('progress_message', models.TextField(blank=True, default='')),
                ('progress_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deployment_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('target_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployment_requests', to='agents.agent')),
                ('target_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_requests', to='containers.container')),
            ],
            options={
                'db_table': 'container_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='container',
            name='created_via_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_containers', to='containers.containerrequest'),
        ),
        migrations.CreateModel(
            name='ContainerTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('simple', 'Simple (single container)'), ('compose', 'Docker Compose')], max_length=10)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('image_options', models.JSONField(blank=True, default=list)),
                ('env_schema', models.JSONField(blank=True, default=list)),
                ('port_schema', models.JSONField(blank=True, default=list)),
                ('default_volumes', models.JSONField(blank=True, default=list)),
                ('compose_yaml', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'container_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='containerrequest',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='containers.containertemplate'),
        ),
        migrations.AddIndex(
            model_name='containerrequest',
            index=models.Index(fields=['requester', 'status'], name='container_r_request_f65f36_idx'),
        ),
        migrations.AddIndex(
            model_name='containerrequest',
            index=models.Index(fields=['status'], name='container_r_status_f6d9fd_idx'),
        ),
    ]
