# Generated by Django 5.1.15 on 2026-05-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentstatusevent'),
        ('containers', '0002_templates_and_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(help_text='Docker event 발생 시각 (UTC)')),
                ('kind', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('die', 'Die'), ('restart', 'Restart'), ('pause', 'Pause'), ('unpause', 'Unpause'), ('kill', 'Kill'), ('oom', 'OOM'), ('health_status', 'Health Status')], max_length=20)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, default='', max_length=20)),
                ('health_status', models.CharField(blank=True, default='', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_events', to='agents.agent')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='containers.container')),
            ],
            options={
                'db_table': 'container_events',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['container', '-ts'], name='container_e_contain_9fbd06_idx'), models.Index(fields=['agent', '-ts'], name='container_e_agent_i_ca7f4a_idx')],
            },
        ),
    ]
