#!/usr/bin/env bash
# Interactively produce a .env file for HyperCube.
# Usage: env-generate.sh /opt/hypercube/.env
#
# Prompts go to stderr, the resulting .env is written to the path given as $1
# (or stdout if no argument).

set -euo pipefail

OUT="${1:-/dev/stdout}"

prompt() {
    # prompt "label" "default" -> echoes user-or-default to stdout
    local label="$1" default="$2" answer
    if [[ -n "${default}" ]]; then
        printf "  %s [%s]: " "${label}" "${default}" >&2
    else
        printf "  %s: " "${label}" >&2
    fi
    read -r answer </dev/tty
    echo "${answer:-$default}"
}

gen_secret() {
    # 50 url-safe chars, no padding
    openssl rand -base64 64 | tr -d '\n=+/' | head -c 50
}

gen_password() {
    openssl rand -base64 32 | tr -d '\n=+/' | head -c 24
}

default_host="$(hostname -I 2>/dev/null | awk '{print $1}')"
[[ -z "${default_host}" ]] && default_host="$(hostname)"

echo "" >&2
echo "HyperCube configuration" >&2
echo "-----------------------" >&2

host=$(prompt "Host IP or DNS name" "${default_host}")
port=$(prompt "Service port" "7003")

# ALLOWED_HOSTS / CSRF / CORS are derived but overridable
allowed_hosts="${host},localhost,127.0.0.1"
csrf_origin="http://${host}:${port}"

secret_key=$(gen_secret)
db_password=$(gen_password)

cat > "${OUT}" <<EOF
# Generated by env-generate.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit values then 'systemctl restart hypercube' to apply.

IMAGE_TAG=latest

# ---- Service exposure ----
HC_HOST=${host}
HC_PORT=${port}

# ---- Django ----
DJANGO_SECRET_KEY=${secret_key}
DJANGO_ALLOWED_HOSTS=${allowed_hosts}
CORS_ALLOWED_ORIGINS=
CORS_ALLOW_ALL_ORIGINS=true
CSRF_TRUSTED_ORIGINS=${csrf_origin}

# ---- PostgreSQL ----
DB_NAME=hypercube
DB_USER=hypercube
DB_PASSWORD=${db_password}
EOF

echo "" >&2
echo "  -> wrote ${OUT}" >&2
